### ISSUE TITLE
multi download - download multiple files for a single template

### ISSUE THREAD

**Issue by wilsonfreitas** [wilsonfreitas/brasa#12]
Tesouro Direto files can be downloaded from the same URL but the arguments vary.
The easy solution is to create different template files, one for each varied argument.
The following questions must be answered:

- How can multiple files be downloaded from a single template?
- How will these files be stored?
- How will the meta be saved? One meta or multiple metas?

Proposed structure to downloaded files.

```
raw/<template>/<varied-argument>/checksum/file
```

another proposal

```
raw/<template>-<varied-argument>/checksum/file
```

Template example:

```yaml
id: td-historical-prices
filename: ~
filetype: CUSTOM
description: Tesouro Direto preços e taxas históricas
downloader:
  verifyssl: false
  function: brasa.downloaders.multi_download
  url: https://cdn.tesouro.gov.br/sistemas-internos/apex/producao/sistemas/sistd/{year}/{contract}_{year}.xls
  format: xls
  use-filename: true
  args:
    year: ~
    contract: ~
  multi:
    contract:
      lft: LFT
      ltn: LTN
      ntnb: NTN-B
      ntnb_principal: NTN-B_Principal
      ntnf: NTN-F
      ntnc: NTN-C

```
